// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: itinerary.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Itinerary {
  public static partial class StationNamesGenerator
  {
    static readonly string __ServiceName = "itinerary.StationNamesGenerator";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Itinerary.RandomStationNamesRequest> __Marshaller_itinerary_RandomStationNamesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Itinerary.RandomStationNamesRequest.Parser));
    static readonly grpc::Marshaller<global::Itinerary.StationNamesResponse> __Marshaller_itinerary_StationNamesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Itinerary.StationNamesResponse.Parser));

    static readonly grpc::Method<global::Itinerary.RandomStationNamesRequest, global::Itinerary.StationNamesResponse> __Method_GetRandomStationNames = new grpc::Method<global::Itinerary.RandomStationNamesRequest, global::Itinerary.StationNamesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRandomStationNames",
        __Marshaller_itinerary_RandomStationNamesRequest,
        __Marshaller_itinerary_StationNamesResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Itinerary.ItineraryReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of StationNamesGenerator</summary>
    [grpc::BindServiceMethod(typeof(StationNamesGenerator), "BindService")]
    public abstract partial class StationNamesGeneratorBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Itinerary.StationNamesResponse> GetRandomStationNames(global::Itinerary.RandomStationNamesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for StationNamesGenerator</summary>
    public partial class StationNamesGeneratorClient : grpc::ClientBase<StationNamesGeneratorClient>
    {
      /// <summary>Creates a new client for StationNamesGenerator</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public StationNamesGeneratorClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for StationNamesGenerator that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public StationNamesGeneratorClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected StationNamesGeneratorClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected StationNamesGeneratorClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Itinerary.StationNamesResponse GetRandomStationNames(global::Itinerary.RandomStationNamesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRandomStationNames(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Itinerary.StationNamesResponse GetRandomStationNames(global::Itinerary.RandomStationNamesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRandomStationNames, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Itinerary.StationNamesResponse> GetRandomStationNamesAsync(global::Itinerary.RandomStationNamesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRandomStationNamesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Itinerary.StationNamesResponse> GetRandomStationNamesAsync(global::Itinerary.RandomStationNamesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRandomStationNames, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override StationNamesGeneratorClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new StationNamesGeneratorClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(StationNamesGeneratorBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetRandomStationNames, serviceImpl.GetRandomStationNames).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, StationNamesGeneratorBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetRandomStationNames, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Itinerary.RandomStationNamesRequest, global::Itinerary.StationNamesResponse>(serviceImpl.GetRandomStationNames));
    }

  }
}
#endregion
